language: node_js
sudo: false
cache:
  directories:
    - node_modules
node_js:
  - "4.1"
before_script:
  - npm install -g gulp
script: gulp test
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
